### PR TITLE
update pages login and register

### PR DESCRIPTION
**Pull request by SauloCoimbr**

### CODE REVIEW

**Review by sdeoliveira-r — COMMENTED** [review]
Viewed

**Review by darkclyan — CHANGES_REQUESTED** [review]
Pleaser format all changes according to the new settings and standards

**Review by davialcantaraa — APPROVED** [review]
Ok

**Review by sdeoliveira-r — COMMENTED** [review]
Ok

**Review by sdeoliveira-r — COMMENTED** [review]
Ok

**Pull request merged**
