### PR TITLE
create todolist component

### PR DESCRIPTION
**Pull request by SauloCoimbr**

### CODE REVIEW

**Review by darkclyan — CHANGES_REQUESTED** [review]
Usar aspas dupla

**Comment by SauloCoimbr** [comment]
Fiz as correções das aspas e acrescentei o calendário.

**Review by sdeoliveira-r — COMMENTED** [review]
Viewed

**Review by darkclyan — CHANGES_REQUESTED** [review]
Pleaser format all changes according to the new settings and standards

**Review by davialcantaraa — APPROVED** [review]
Ok

**Pull request merged**
